plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

java {
    sourceCompatibility = '21'
}

dependencies {
    api 'io.grpc:grpc-stub:1.62.2'
    api 'io.grpc:grpc-protobuf:1.62.2'
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.3'
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.62.2'
        }
    }
    generateProtoTasks {
        all().configureEach { task ->
            task.plugins {
                grpc {}
            }
        }
    }
}

sourceSets {
    main {
        java {
            srcDirs += "$buildDir/generated/source/proto/main/java"
            srcDirs += "$buildDir/generated/source/proto/main/grpc"
        }
    }
}

compileJava {
    dependsOn 'generateProto'
    options.encoding = 'UTF-8'
}
