spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# ????????? Spring Boot ??????
spring.main.banner-mode=off

# ????????? ???????????
logging.charset.console=UTF-8
logging.file.charset=UTF-8