# Настройка автоматического триажа уязвимостей
fail-on-severity: critical
ignore:
  # Сюда можно добавлять CVE, которые имеют низкий EPSS и не критичны для инфраструктуры
  - vulnerability: CVE-2016-2781 # Пример игнорирования старой системной