plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'application'
}

java {
    sourceCompatibility = '21'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    implementation 'net.devh:grpc-server-spring-boot-starter:2.15.0.RELEASE'
    implementation project(':telemetry-proto')
    implementation project(':satellite-events')
    implementation 'org.springframework.kafka:spring-kafka'

    runtimeOnly 'org.postgresql:postgresql'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'com.h2database:h2'
}

application {
    mainClass = 'com.satellite.telemetry.TelemetryServiceApplication'
}

tasks.named('bootJar') {
    archiveFileName = 'telemetry-service.jar'
}

test {
    useJUnitPlatform()
}

compileJava {
    options.encoding = 'UTF-8'
}
